package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ITest", targetNamespace = "http://www.example.org/zy/")
public interface ITest {


    /**
     * 
     * @param param
     * @param otherArg
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "fnResResult", targetNamespace = "")
    @RequestWrapper(localName = "fn", targetNamespace = "http://www.example.org/zy/", className = "org.example.zy.Fn")
    @ResponseWrapper(localName = "fnRes", targetNamespace = "http://www.example.org/zy/", className = "org.example.zy.FnResType")
    public String fn(
        @WebParam(name = "param", targetNamespace = "")
        String param,
        @WebParam(name = "otherArg", targetNamespace = "")
        int otherArg);

}
