
package server;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMyService", targetNamespace = "http://www.example.org/zy/")
public interface IMyService {


    /**
     * 
     * @param user
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
//    @RequestWrapper(localName = "add", targetNamespace = "http://www.example.org/zy/")
//    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://www.example.org/zy/", className = "org.example.zy.AddResponse")
    public boolean add(
        @WebParam(name = "user", targetNamespace = "")
        User user);

    /**
     * 
     * @return
     *     returns java.util.List<org.example.zy.User>
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
//    @RequestWrapper(localName = "list", targetNamespace = "http://www.example.org/zy/", className = "org.example.zy.List")
//    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://www.example.org/zy/", className = "org.example.zy.ListResponse")
    public List<User> list();

}
