package _junitTest.yun;

import static org.junit.Assert.*;

import java.util.Arrays;
import java.util.List;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Ignore;
import org.junit.Test;

public class ATest {

	@BeforeClass
	public static void beforeClass(){
		System.out.println("-----before class-----");
	}
	
	@Before
	public void before(){
		System.out.println("+++before++");
	}
	
	@After
	public void after(){
		System.out.println("+++after++");
	}
	
	@AfterClass
	public static void afterClass(){
		System.out.println("----after class----");
	}
	
	
	@Test
	public void testAdd() {
		int z = new A().add(1, 2);
		assertEquals(z, 3);
	}
	
	@Test
	public void test2(){
		assertEquals(new A().name(), ("≤‚ ‘"));
		System.out.println("test2");
	}
	
	@Ignore
	@Test
	public void ignore(){
		System.out.println("this is ignore method");
	}
	@Test 
	public void type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertNotNull(A.class);
	}

	@Test
	public void test(){
		List<Object[]> list = Arrays.asList(new Object[][]{{0,1},{-1,-2}});
		int[][][] a = new int[][][]{{{1,2,3}},{{4,5,6}}};
		System.out.println(a[0][1]);
	}
	
	
}
